spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/CalvinRefact
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
        #hibernate를 통한 sql 출력
        show_sql: true
        use_sql_comments: true
        #logger를 통한 sql 출력
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace